CREATE TABLE retry_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_key VARCHAR(255) NOT NULL UNIQUE,
    job_type VARCHAR(32) NOT NULL,
    source_topic VARCHAR(255) NOT NULL,
    reference_id VARCHAR(255),
    notification_email VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    payload TEXT NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    last_attempt_at TIMESTAMP,
    next_retry_at TIMESTAMP NOT NULL,
    data_status VARCHAR(32) NOT NULL,
    data_message TEXT,
    send_email_status VARCHAR(32) NOT NULL,
    send_email_message TEXT,
    update_retry_jobs_status VARCHAR(32) NOT NULL,
    update_retry_jobs_message TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_retry_jobs_type_status_next_retry
    ON retry_jobs (job_type, status, next_retry_at);

CREATE TABLE payments_retry_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retry_job_id BIGINT NOT NULL UNIQUE,
    reference_id VARCHAR(255),
    orden_id VARCHAR(255) NOT NULL,
    monto NUMERIC(19, 2) NOT NULL,
    pago_estado VARCHAR(100),
    execution_status VARCHAR(32) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_payments_retry_jobs_retry_job
        FOREIGN KEY (retry_job_id) REFERENCES retry_jobs (id)
);

CREATE TABLE order_retry_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retry_job_id BIGINT NOT NULL UNIQUE,
    reference_id VARCHAR(255),
    producto_id VARCHAR(255) NOT NULL,
    usuario_id VARCHAR(255) NOT NULL,
    orden_status VARCHAR(100),
    execution_status VARCHAR(32) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_order_retry_jobs_retry_job
        FOREIGN KEY (retry_job_id) REFERENCES retry_jobs (id)
);

CREATE TABLE product_retry_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retry_job_id BIGINT NOT NULL UNIQUE,
    reference_id VARCHAR(255),
    nombre VARCHAR(255) NOT NULL,
    precio NUMERIC(19, 2) NOT NULL,
    execution_status VARCHAR(32) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_product_retry_jobs_retry_job
        FOREIGN KEY (retry_job_id) REFERENCES retry_jobs (id)
);
