CREATE TABLE envios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL UNIQUE,
    orden_id VARCHAR(255) NOT NULL UNIQUE,
    usuario_id VARCHAR(255),
    notification_email VARCHAR(255),
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    processed_at TIMESTAMP,
    last_error TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_envios_processed_created_at
    ON envios (processed, created_at);
